export const sheetData = {
  policies: {
    'portfolio.pm.operation_data.attachment': true,
    'portfolio.pm.operation_data.set_editable_area': true,
    'portfolio.pm.operation_data.export': true,
    'portfolio.pm.operation_data.upload_attachment': true,
    'portfolio.pm.operation_data.save': true,
    'portfolio.pm.operation_data.audit': false,
    'portfolio.pm.operation_data.publish': false,
    'portfolio.pm.operation_data.rollback': true,
    'portfolio.pm.operation_data.import': true,
  },
  whiteProperties: null,
  id: '227D83C19CA548D5A415F4C70671E7A3',
  companyId: 'F6DAA9CC5CA44290BF182C57276B74AE',
  company: {
    id: 'F6DAA9CC5CA44290BF182C57276B74AE',
    name: '交割日期-2023-5-30',
    dls: [
      {
        userId: 911,
        userName: '周海涛',
        userNameEn: 'staceyzhou',
        statusId: 1,
        email: null,
        isFrozen: 0,
        frozenAt: null,
      },
    ],
    followers: [],
    writers: [
      {
        id: 1000000001,
        type: {
          id: 'external',
          name: '被投公司用户',
          extra: null,
        },
        account: 'test1@qq.com',
        name: 'test1',
        language: {
          id: 'zh',
          name: '中文',
          extra: null,
        },
        companies: null,
      },
    ],
    audits: [],
  },
  type: {
    id: 'business',
    name: '运营数据',
    extra: null,
  },
  version: '2024Q1v6.0',
  shareVersion: {
    id: '8E3CDF1F46744E8FBFF3C2BE75174835',
    tableId: '227D83C19CA548D5A415F4C70671E7A3',
    type: {
      id: 'share',
      name: '共享版本',
      extra: null,
    },
    version: '2024Q1v6.0',
    remark: null,
    status: {
      id: 'new',
      name: '未打开',
      extra: null,
    },
    createTime: '2024-05-10T06:08:42Z',
    updateTime: '2024-05-10T06:08:42Z',
    sheets: null,
  },
  localVersion: {
    id: '220DFCA8D4C547E9800944C0A0FDEAA9',
    tableId: '227D83C19CA548D5A415F4C70671E7A3',
    type: {
      id: 'local',
      name: '个人版本',
      extra: null,
    },
    version: '2024Q1v6.2',
    remark: null,
    status: {
      id: 'filling',
      name: '填写中',
      extra: null,
    },
    createTime: '2024-05-31T07:28:53Z',
    updateTime: '2024-05-31T07:28:53Z',
    sheets: null,
  },
  latestVersion: {
    id: '220DFCA8D4C547E9800944C0A0FDEAA9',
    tableId: '227D83C19CA548D5A415F4C70671E7A3',
    type: {
      id: 'local',
      name: '个人版本',
      extra: null,
    },
    version: '2024Q1v6.2',
    remark: null,
    status: {
      id: 'filling',
      name: '填写中',
      extra: null,
    },
    createTime: '2024-05-31T07:28:53Z',
    updateTime: '2024-05-31T07:28:53Z',
    sheets: null,
  },
  directoryId: '890D84C07CA14F6AA4D53439A9B1DDE7',
  record: {
    policies: {
      'portfolio.pm.operation_data.set_editable_area': true,
      'portfolio.pm.operation_data.export': true,
      'portfolio.pm.operation_data.save': true,
      'portfolio.pm.operation_data.audit': false,
      'portfolio.pm.operation_data.publish': false,
      'portfolio.pm.operation_data.rollback': true,
      'portfolio.pm.operation_data.import': true,
    },
    whiteProperties: null,
    id: 'C1C0CA4CE7AD4E798970B39FD961F933',
    fillingStatus: {
      id: 'filling',
      name: '填写中',
      extra: null,
    },
    dataPerformance: null,
  },
  recordId: 'C1C0CA4CE7AD4E798970B39FD961F933',
  fillingStatus: {
    id: 'filling',
    name: '填写中',
    extra: null,
  },
  dataPerformance: null,
  createBy: null,
  creator: null,
  updateBy: 25232,
  createTime: '2023-12-07T02:13:55Z',
  updateTime: '2024-05-10T06:08:42Z',
  sheets: [
    {
      id: '2ECB87DFF99A4A95A07735A748350CEB',
      tableId: '227D83C19CA548D5A415F4C70671E7A3',
      version: '2024Q1v6.2',
      name: '交割日期-2023-5-30',
      color: null,
      index: 'Sheet_1spixw0ixxw9_1701915234631',
      status: 1,
      order: 0,
      hide: null,
      row: 40,
      column: 30,
      defaultRowHeight: null,
      defaultColWidth: null,
      calcChain: null,
      celldata: [
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '111',
            m: '1111',
          },
          r: 2,
          c: 0,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 2,
          c: 1,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '说明',
            m: '说明',
          },
          r: 2,
          c: 2,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '单位',
            m: '单位',
          },
          r: 2,
          c: 3,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            bg: 'rgb(7, 55, 99)',
            ff: '1',
            fc: 'rgb(255, 255, 255)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 0,
            v: '2022-Q2',
            m: '2022-Q2',
          },
          r: 2,
          c: 4,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            bg: 'rgb(7, 55, 99)',
            ff: '1',
            fc: 'rgb(255, 255, 255)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 0,
            v: '2022-Q3',
            m: '2022-Q3',
          },
          r: 2,
          c: 5,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            bg: 'rgb(7, 55, 99)',
            ff: '1',
            fc: 'rgb(255, 255, 255)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 0,
            v: '2022-Q4',
            m: '2022-Q4',
          },
          r: 2,
          c: 6,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            bg: 'rgb(7, 55, 99)',
            ff: '1',
            fc: 'rgb(255, 255, 255)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 0,
            v: '2023-Q1',
            m: '2023-Q1',
          },
          r: 2,
          c: 7,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            bg: 'rgb(7, 55, 99)',
            ff: '1',
            fc: 'rgb(255, 255, 255)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 0,
            v: '2023-Q2',
            m: '2023-Q2',
          },
          r: 2,
          c: 8,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            bg: 'rgb(7, 55, 99)',
            ff: '1',
            fc: 'rgb(255, 255, 255)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 0,
            v: '2023-Q3',
            m: '2023-Q3',
          },
          r: 2,
          c: 9,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            bg: 'rgb(7, 55, 99)',
            ff: '1',
            fc: 'rgb(255, 255, 255)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 0,
            v: '2023-Q4',
            m: '2023-Q4',
          },
          r: 2,
          c: 10,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            bg: 'rgb(7, 55, 99)',
            ff: '1',
            fc: 'rgb(255, 255, 255)',
            bl: 1,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 0,
            v: '2024-Q1',
            m: '2024-Q1',
          },
          r: 2,
          c: 11,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '公司流水总数',
            m: '公司流水总数',
          },
          r: 3,
          c: 1,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 3,
          c: 2,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: 'CNY',
            m: 'CNY',
          },
          r: 3,
          c: 3,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: '1000',
            m: '1000',
          },
          r: 3,
          c: 4,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 3,
          c: 5,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 3,
          c: 6,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 3,
          c: 7,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 3,
          c: 8,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 3,
          c: 9,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 3,
          c: 10,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 3,
          c: 11,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '本季度DAU峰值',
            m: '本季度DAU峰值',
          },
          r: 4,
          c: 1,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 4,
          c: 2,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '#',
            m: '#',
          },
          r: 4,
          c: 3,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 4,
          c: 4,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 4,
          c: 5,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 4,
          c: 6,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 4,
          c: 7,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 4,
          c: 8,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 4,
          c: 9,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 4,
          c: 10,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 4,
          c: 11,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '在运营（已上线）游戏数量（只看游戏数量，不用版本分开）',
            m: '在运营（已上线）游戏数量（只看游戏数量，不用版本分开）',
          },
          r: 5,
          c: 1,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 5,
          c: 2,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '#',
            m: '#',
          },
          r: 5,
          c: 3,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 5,
          c: 4,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 5,
          c: 5,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 5,
          c: 6,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 5,
          c: 7,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 5,
          c: 8,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 5,
          c: 9,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 5,
          c: 10,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 5,
          c: 11,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '当季流水总数里，来自非中国大陆地区百分比',
            m: '当季流水总数里，来自非中国大陆地区百分比',
          },
          r: 6,
          c: 1,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 6,
          c: 2,
        },
        {
          v: {
            ct: {
              fa: '@',
              t: 's',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '%',
            m: '%',
          },
          r: 6,
          c: 3,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 6,
          c: 4,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 6,
          c: 5,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 6,
          c: 6,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 6,
          c: 7,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 6,
          c: 8,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 6,
          c: 9,
        },
        {
          v: {
            ct: {
              fa: '0%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 6,
          c: 10,
        },
        {
          v: {
            ct: {
              fa: '0%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 6,
          c: 11,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '当季用户总数里，来自非中国大陆地区百分比',
            m: '当季用户总数里，来自非中国大陆地区百分比',
          },
          r: 7,
          c: 1,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 7,
          c: 2,
        },
        {
          v: {
            ct: {
              fa: '@',
              t: 's',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '%',
            m: '%',
          },
          r: 7,
          c: 3,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 7,
          c: 4,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 7,
          c: 5,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 7,
          c: 6,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 7,
          c: 7,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 7,
          c: 8,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 7,
          c: 9,
        },
        {
          v: {
            ct: {
              fa: '0.00%',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 7,
          c: 10,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 7,
          c: 11,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: 'MAU最大的单款游戏名称',
            m: 'MAU最大的单款游戏名称',
          },
          r: 8,
          c: 1,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 8,
          c: 2,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 8,
          c: 3,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 8,
          c: 4,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 8,
          c: 5,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 8,
          c: 6,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 8,
          c: 7,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 8,
          c: 8,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 8,
          c: 9,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 8,
          c: 10,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 8,
          c: 11,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: 'MAU最大的单款游戏MAU数',
            m: 'MAU最大的单款游戏MAU数',
          },
          r: 9,
          c: 1,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 9,
          c: 2,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '#',
            m: '#',
          },
          r: 9,
          c: 3,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 9,
          c: 4,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 9,
          c: 5,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 9,
          c: 6,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 9,
          c: 7,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 9,
          c: 8,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 9,
          c: 9,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 9,
          c: 10,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 9,
          c: 11,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '在研发（未上线）游戏数量（只看有项目组在开发的）',
            m: '在研发（未上线）游戏数量（只看有项目组在开发的）',
          },
          r: 10,
          c: 1,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 10,
          c: 2,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'g',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: '#',
            m: '#',
          },
          r: 10,
          c: 3,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 10,
          c: 4,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 10,
          c: 5,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 10,
          c: 6,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 10,
          c: 7,
        },
        {
          v: {
            ct: null,
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 1,
            v: null,
            m: null,
          },
          r: 10,
          c: 8,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 10,
          c: 9,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 10,
          c: 10,
        },
        {
          v: {
            ct: {
              fa: 'General',
              t: 'n',
            },
            ff: '1',
            fc: 'rgb(0, 0, 0)',
            bl: 0,
            it: 0,
            fs: 9,
            vt: 0,
            ht: 2,
            v: null,
            m: null,
          },
          r: 10,
          c: 11,
        },
      ],
      config: {
        merge: {},
        rowlen: {},
        columnlen: {
          '0': 30,
        },
        rowhidden: null,
        colhidden: null,
        borderInfo: null,
        authority: null,
      },
      scrollLeft: 0,
      scrollTop: 0,
      frozen: null,
      zoomRatio: 1,
      editable: null,
      isDefault: 1,
    },
  ],
  displayArea: null,
};
